### PR TITLE
Codeplex has frequent issues and will no longer be updated after...

### PR DESCRIPTION
**Pull request by scotthain**
...November 6th, 2017. This cuts over to the github repository. I expect this should be a major version bump since it removes the Codeplex functionality and changes the wix toolkit version.

Signed-off-by: Scott Hain <shain@chef.io>

### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by scotthain** [comment]
@chef-cookbooks/engineering-services

**Comment by tduffield** [comment]
Do we need to bump the metadata?

**Comment by scotthain** [comment]
@tas50 Looks like this repo is not active in travis-ci... Should it be? (Also wasn't sure if I should bump metadata or if y'all do that as part of the release process?)

**Comment by iennae** [comment]
It shouldn't be active in travis-ci. We bump metadata when we release.

**Comment by scotthain** [comment]
@iennae I'm not sure why it's saying it's required :(

**Comment by iennae** [comment]
I couldn't figure out what I needed to do to remove it :)

**Pull request merged**
