### PR TITLE
Update to WIX 3.10

### PR DESCRIPTION
**Pull request by chefsalim**
Upgrade to the latest WIX toolset.

cc @chef-cookbooks/client-windows @schisamo

### CODE REVIEW

**Comment by schisamo** [comment]
:+1: once Travis is happy.

**Comment by chefsalim** [comment]
Note: The Travis errors are rubocop issues which are unrelated to and not introduced by this change.  There is a separate effort by @tas50 to clean up cookbook rubocop failures.

**Comment by tas50** [comment]
Rubocop fix pushed to master

**Comment by schisamo** [comment]
@chefsalim Please rebase this branch on master.

**Pull request merged**
